version: "3.8"

services:
    forecast_service:
        build: ./forecast-service
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - ./forecast-service/:/app/
        ports:
            - 8001:8000

    current_service:
        build: ./current-service
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - ./current-service/:/app/
        ports:
            - 8002:8000

    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./nginx_conf.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - forecast_service
            - current_service
